baseURL: 'https://4ndrs.xyz/'
languageCode: en-us
title: 4ndrs.xyz
theme: hugo-coder
publishDir: public
languagecode: en
defaultcontentlanguage: en
paginate: 10
canonifyurls: true
pygmentsstyle: friendly
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
#disqusShortname: 4ndrs-xyz
googleAnalytics: G-3KVF1J8CS4
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
  - name: keywords
    weight: 100
  - name: tags
    weight: 100
params:
  author: Andreas Siegel
  description: some guy passionate about IT and other things
  keywords: 'blog,developer,personal'
  info: some guy passionate about IT and other things
  avatarurl: images/4ndrs.jpg
  footercontent: ''
  dateformat: 'January 2, 2006'
  hideRelated: false
  hideFooter: false
  hideCredits: true
  hideCopyright: false
  relatedCount: 3
  since: 2017
  commit: 'https://github.com/luizdepra/hugo-coder/tree/'
  rtl: false
  colorscheme: light
  maxSeeAlsoItems: 5
  custom_css: []
  custom_js: []
  social:
    - name: Github
      icon: fab fa-github
      weight: 1
      url: 'https://github.com/andreassiegel/'
    - name: Stack Overflow
      icon: fab fa-stack-overflow
      weight: 2
      url: 'https://stackoverflow.com/users/6418426/andreas-siegel'
    - name: dev.to
      icon: fab fa-dev
      weight: 3
      url: 'https://dev.to/andreassiegel'
    - name: Instagram
      icon: fab fa-instagram
      weight: 4
      url: 'https://www.instagram.com/andreassiegel'
    - name: 500px
      icon: fab fa-500px
      weight: 5
      url: 'https://500px.com/andreassiegel'
    - name: Facebook
      icon: fab fa-facebook
      weight: 6
      url: 'https://www.facebook.com/andreas.siegel.chemnitz'
    - name: LinkedIn
      icon: fab fa-linkedin
      weight: 8
      url: 'https://www.linkedin.com/in/andreassiegel'
taxonomies:
  category: categories
  series: series
  tag: tags
languages:
  en:
    languagename: English
    menu:
      main:
        - name: About
          weight: 1
          url: about/
        - name: Blog
          weight: 2
          url: posts/
        - name: Categories
          weight: 3
          url: categories/
        - name: Contact me
          weight: 5
          url: contact/
security:
  exec:
    allow:
      - '^(dart-)?sass(-embedded)?$'
      - '^go$'
      - '^npx$'
      - '^postcss$'
      - '^asciidoctor$'
